"""
OpenSCAD Engine

Implementation of CAD engine for OpenSCAD.
"""

import re
import subprocess
from typing import Dict, Any, Optional, List
from pathlib import Path

from ..base_engine import BaseCADEngine, CodeValidationResult, MeshAnalysis


class OpenSCADEngine(BaseCADEngine):
    """
    CAD engine for OpenSCAD.
    
    Generates OpenSCAD code and can export to STL using openscad command.
    """
    
    def __init__(self, output_dir: str = "output", openscad_path: Optional[str] = None, **kwargs):
        """
        Initialize OpenSCAD engine.
        
        Args:
            output_dir: Directory for output files
            openscad_path: Path to OpenSCAD executable (auto-detected if None)
            **kwargs: Additional configuration
        """
        super().__init__(output_dir=output_dir, **kwargs)
        self.openscad_path = openscad_path or self._find_openscad()
    
    def _find_openscad(self) -> Optional[str]:
        """Try to find OpenSCAD executable in system PATH."""
        import shutil
        return shutil.which("openscad")
    
    def generate_code(
        self,
        shape: str,
        parameters: Optional[Dict[str, Any]] = None,
        operation: Optional[str] = None,
        **kwargs
    ) -> str:
        """
        Generate OpenSCAD code for a given shape.
        
        Args:
            shape: Type of shape (cube, sphere, cylinder, etc.)
            parameters: Shape parameters
            operation: Optional operation (hollow, centered)
            
        Returns:
            OpenSCAD code string
        """
        if parameters is None:
            parameters = {}
            
        shape_lower = shape.lower()
        
        # Generate base shape code
        if shape_lower == "cube":
            code = self._generate_cube(parameters)
        elif shape_lower in ["sphere", "ball"]:
            code = self._generate_sphere(parameters)
        elif shape_lower == "cylinder":
            code = self._generate_cylinder(parameters)
        elif shape_lower == "cone":
            code = self._generate_cone(parameters)
        elif shape_lower == "torus":
            code = self._generate_torus(parameters)
        elif shape_lower == "pyramid":
            code = self._generate_pyramid(parameters)
        else:
            code = self._generate_cube(parameters)  # Default to cube
        
        # Apply operations
        if operation:
            code = self._apply_operation(code, operation, parameters, shape_lower)
        
        # Add header
        header = f"// Generated by CadGPT\n"
        header += f"// Shape: {shape}\n"
        header += f"// Parameters: {parameters}\n\n"
        
        return header + code
    
    def _generate_cube(self, params: Dict[str, Any]) -> str:
        """Generate cube code."""
        size = params.get("size", 100)
        centered = params.get("centered", False)
        
        return f'cube([{size}, {size}, {size}], center={str(centered).lower()});'
    
    def _generate_sphere(self, params: Dict[str, Any]) -> str:
        """Generate sphere code."""
        radius = params.get("radius", 50)
        segments = params.get("segments", 50)
        
        return f'sphere(r={radius}, $fn={segments});'
    
    def _generate_cylinder(self, params: Dict[str, Any]) -> str:
        """Generate cylinder code."""
        height = params.get("height", 100)
        radius = params.get("radius", 25)
        segments = params.get("segments", 50)
        
        return f'cylinder(h={height}, r={radius}, $fn={segments});'
    
    def _generate_cone(self, params: Dict[str, Any]) -> str:
        """Generate cone code."""
        height = params.get("height", 100)
        radius1 = params.get("radius", 25)
        radius2 = params.get("top_radius", 0)
        segments = params.get("segments", 50)
        
        return f'cylinder(h={height}, r1={radius1}, r2={radius2}, $fn={segments});'
    
    def _generate_torus(self, params: Dict[str, Any]) -> str:
        """Generate torus code."""
        outer_radius = params.get("outer_radius", 50)
        inner_radius = params.get("inner_radius", 10)
        segments = params.get("segments", 50)
        
        return f'''rotate_extrude($fn={segments})
translate([{{outer_radius}}, 0, 0])
circle(r={inner_radius}, $fn={segments});'''
    
    def _generate_pyramid(self, params: Dict[str, Any]) -> str:
        """Generate pyramid code."""
        base_size = params.get("base_size", 100)
        height = params.get("height", 100)
        
        return f'''linear_extrude(height={height}, scale=0)
square([{base_size}, {base_size}], center=true);'''
    
    def _apply_operation(
        self,
        code: str,
        operation: str,
        parameters: Dict[str, Any],
        shape: str
    ) -> str:
        """Apply operation to generated code."""
        
        if operation == "hollow":
            thickness = parameters.get("thickness", 5)
            
            if shape == "cube":
                size = parameters.get("size", 100)
                inner_size = size - 2 * thickness
                return f"""difference() {{
    {code}
    cube([{inner_size}, {inner_size}, {inner_size}], center=true);
}}"""
            
            elif shape == "sphere":
                radius = parameters.get("radius", 50)
                inner_radius = radius - thickness
                return f"""difference() {{
    {code}
    sphere(r={inner_radius});
}}"""
            
            elif shape == "cylinder":
                height = parameters.get("height", 100)
                radius = parameters.get("radius", 25)
                inner_radius = radius - thickness
                return f"""difference() {{
    {code}
    cylinder(h={height + 1}, r={inner_radius});
}}"""
        
        elif operation == "centered":
            # Wrap with translate to center
            return f"translate([0, 0, 0])\n{code}"
        
        return code
    
    def validate_code(self, code: str) -> CodeValidationResult:
        """
        Validate OpenSCAD code syntax.
        
        Args:
            code: OpenSCAD code to validate
            
        Returns:
            CodeValidationResult with validation status
        """
        errors = []
        warnings = []
        
        # Check for balanced braces
        open_braces = code.count('{')
        close_braces = code.count('}')
        if open_braces != close_braces:
            errors.append(f"Unbalanced braces: {open_braces} open, {close_braces} close")
        
        # Check for balanced parentheses
        open_parens = code.count('(')
        close_parens = code.count(')')
        if open_parens != close_parens:
            errors.append(f"Unbalanced parentheses: {open_parens} open, {close_parens} close")
        
        # Check for semicolons at end of statements
        lines = code.split('\n')
        for i, line in enumerate(lines):
            stripped = line.strip()
            if stripped and not stripped.startswith('//'):
                if any(stripped.startswith(kw) for kw in ['cube', 'sphere', 'cylinder', 'difference', 'union', 'intersection']):
                    if not stripped.endswith(';') and not stripped.endswith('{') and not stripped.endswith('}'):
                        if not any(stripped.startswith(x) for x in ['module', 'function']):
                            warnings.append(f"Line {i+1}: Statement may be missing semicolon")
        
        # Check for common syntax errors
        if re.search(r'\b(module|function)\s+\w+\s*\([^)]*\)\s*;', code):
            errors.append("Module/function definition has semicolon instead of braces")
        
        is_valid = len(errors) == 0
        
        report = "✓ VÁLIDO" if is_valid else "✗ INVÁLIDO\n"
        if errors:
            report += "\nErrores:\n" + "\n".join(f"  - {e}" for e in errors)
        if warnings:
            report += f"\nAdvertencias ({len(warnings)}):\n" + "\n".join(f"  - {w}" for w in warnings[:5])
        
        return CodeValidationResult(
            is_valid=is_valid,
            report=report,
            errors=errors,
            warnings=warnings,
            syntax_valid=len(errors) == 0,
            geometry_valid=True,
            topology_valid=True
        )
    
    def execute_code(self, code: str) -> bool:
        """
        Execute OpenSCAD code to check for errors.
        
        Args:
            code: OpenSCAD code to execute
            
        Returns:
            True if execution successful
        """
        if not self.openscad_path:
            return False
        
        # Save code to temp file
        temp_file = self.output_dir / "temp.scad"
        with open(temp_file, 'w') as f:
            f.write(code)
        
        try:
            result = subprocess.run(
                [self.openscad_path, "-o", str(self.output_dir / "temp.stl"), str(temp_file)],
                capture_output=True,
                text=True,
                timeout=30
            )
            return result.returncode == 0
        except Exception:
            return False
    
    def export_mesh(
        self,
        code: str,
        filepath: str,
        format: str = "stl"
    ) -> Optional[str]:
        """
        Export OpenSCAD code to mesh file.
        
        Args:
            code: OpenSCAD code
            filepath: Output file path
            format: Export format (default: stl)
            
        Returns:
            Path to exported file or None
        """
        if not self.openscad_path:
            return None
        
        # Save code
        scad_file = self.output_dir / "export.scad"
        with open(scad_file, 'w') as f:
            f.write(code)
        
        # Determine output path
        output_path = Path(filepath)
        if not output_path.is_absolute():
            output_path = self.output_dir / filepath
        
        format_ext = format.lower().lstrip('.')
        if output_path.suffix != f'.{format_ext}':
            output_path = output_path.with_suffix(f'.{format_ext}')
        
        try:
            subprocess.run(
                [self.openscad_path, "-o", str(output_path), str(scad_file)],
                capture_output=True,
                timeout=60
            )
            return str(output_path)
        except Exception:
            return None
    
    def analyze_mesh(self, code: str) -> MeshAnalysis:
        """
        Analyze mesh properties from OpenSCAD code.
        
        Args:
            code: OpenSCAD code
            
        Returns:
            MeshAnalysis with properties
        """
        # Basic analysis without actual mesh generation
        # In production, would use trimesh or similar
        
        return MeshAnalysis(
            vertices=0,
            faces=0,
            edges=0,
            is_manifold=True,
            is_watertight=True,
            volume=0.0,
            surface_area=0.0,
            bounding_box={"min": [0, 0, 0], "max": [100, 100, 100]}
        )
    
    def get_supported_shapes(self) -> List[str]:
        """Get list of supported shapes."""
        return ["cube", "sphere", "cylinder", "cone", "torus", "pyramid"]
    
    def get_supported_formats(self) -> List[str]:
        """Get list of supported export formats."""
        return ["stl", "off", "dxf", "svg", "png"]
    
    def export_to_file(self, code: str, output_path: str, format: str = "stl") -> bool:
        """
        Exporta el código OpenSCAD a un archivo físico.
        
        Args:
            code: Código OpenSCAD a guardar.
            output_path: Ruta completa del archivo de salida (ej: C:/models/cubo.stl).
            format: Formato de exportación ('scad' o 'stl').
            
        Returns:
            True si éxito, False si fallo.
        """
        import os
        import subprocess
        
        try:
            # Asegurar directorio
            dir_path = os.path.dirname(output_path)
            if dir_path:
                os.makedirs(dir_path, exist_ok=True)
            
            # Determinar extensiones
            file_ext = os.path.splitext(output_path)[1].lower()
            
            # 1. Guardar archivo .scad siempre (necesario para compilar)
            temp_scad = output_path.replace(file_ext, '.scad')
            if file_ext == '.scad':
                temp_scad = output_path
            
            with open(temp_scad, 'w', encoding='utf-8') as f:
                f.write(code)
            
            print(f"[OpenSCAD] Código guardado en: {temp_scad}")
            
            # Si solo queríamos el .scad, terminamos aquí
            if file_ext == '.scad':
                return True
            
            # 2. Intentar compilar a STL/OBJ/etc usando openscad
            if not self.openscad_path or not os.path.exists(self.openscad_path):
                print("[OpenSCAD] Advertencia: Ejecutable no encontrado. Solo se generó el archivo .scad")
                print("[OpenSCAD] Para generar STL, instala OpenSCAD y configura la ruta.")
                # Devolvemos True porque el .scad se generó correctamente
                return True 
            
            # Comando de exportación: openscad -o output.stl input.scad
            cmd = [
                self.openscad_path,
                "-o", output_path,
                temp_scad
            ]
            
            print(f"[OpenSCAD] Ejecutando: {' '.join(cmd)}")
            
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=60
            )
            
            if result.returncode == 0 and os.path.exists(output_path):
                print(f"[OpenSCAD] Exportación exitosa a: {output_path}")
                return True
            else:
                if result.stderr:
                    print(f"[OpenSCAD] Error en compilación: {result.stderr}")
                # Aún devolvemos True porque el .scad se generó
                return True
                
        except Exception as e:
            print(f"[OpenSCAD] Excepción al exportar: {str(e)}")
            return False
